services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: inspectr
      POSTGRES_PASSWORD: inspectr
      POSTGRES_DB: inspectr
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata:
